// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7o0KGco-qkIZX0cJX0bPqN94L1-gofc',
    appId: '1:370342781117:web:3215c62052123206b6d7d4',
    messagingSenderId: '370342781117',
    projectId: 'gesport-26b1d',
    authDomain: 'gesport-26b1d.firebaseapp.com',
    storageBucket: 'gesport-26b1d.firebasestorage.app',
    measurementId: 'G-2TRK580H7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjh18NPjMPmAl1wuwf1SrKHpPNL_OUG98',
    appId: '1:370342781117:android:c9a198dd449d9530b6d7d4',
    messagingSenderId: '370342781117',
    projectId: 'gesport-26b1d',
    storageBucket: 'gesport-26b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4PPqv67XKJDX9Juk5Xb8Xba4fDeTGFQ',
    appId: '1:370342781117:ios:66921057dbc6f15cb6d7d4',
    messagingSenderId: '370342781117',
    projectId: 'gesport-26b1d',
    storageBucket: 'gesport-26b1d.firebasestorage.app',
    iosBundleId: 'com.example.gesport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl4PPqv67XKJDX9Juk5Xb8Xba4fDeTGFQ',
    appId: '1:370342781117:ios:66921057dbc6f15cb6d7d4',
    messagingSenderId: '370342781117',
    projectId: 'gesport-26b1d',
    storageBucket: 'gesport-26b1d.firebasestorage.app',
    iosBundleId: 'com.example.gesport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7o0KGco-qkIZX0cJX0bPqN94L1-gofc',
    appId: '1:370342781117:web:c849c76f9d9f4e4bb6d7d4',
    messagingSenderId: '370342781117',
    projectId: 'gesport-26b1d',
    authDomain: 'gesport-26b1d.firebaseapp.com',
    storageBucket: 'gesport-26b1d.firebasestorage.app',
    measurementId: 'G-QXR3RBLKPW',
  );
}
